# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gallery.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(675, 320)
        Form.setStyleSheet("background-color: rgb(241, 219, 253);")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 675, 320))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.p2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.p2.setObjectName("p2")
        self.gridLayout.addWidget(self.p2, 0, 1, 1, 1)
        self.p3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.p3.setObjectName("p3")
        self.gridLayout.addWidget(self.p3, 0, 2, 1, 1)
        self.p1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.p1.setObjectName("p1")
        self.gridLayout.addWidget(self.p1, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Моя галерея"))
        self.p2.setText(_translate("Form", "Пока тут ничего нет"))
        self.p3.setText(_translate("Form", "Пока тут ничего нет"))
        self.p1.setText(_translate("Form", "Пока тут ничего нет"))
