# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project/registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(435, 174)
        MainWindow.setStyleSheet("background-color: rgb(241, 219, 253);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 431, 151))
        self.tabWidget.setStyleSheet("background-color: rgb(241, 219, 253);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 421, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(97, 53, 131);")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setStyleSheet("color: rgb(97, 53, 131);")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.login = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.login.setObjectName("login")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.login)
        self.password = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password)
        self.entry = QtWidgets.QPushButton(self.formLayoutWidget)
        self.entry.setStyleSheet("color: rgb(97, 53, 131);\n"
"background-color: rgb(220, 138, 221);")
        self.entry.setObjectName("entry")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.entry)
        self.tabWidget.addTab(self.tab, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.widget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 421, 121))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_3.setStyleSheet("color: rgb(97, 53, 131);")
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.login1 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.login1.setObjectName("login1")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.login1)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_4.setStyleSheet("color:rgb(97, 53, 131)")
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.password1 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.password1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password1.setObjectName("password1")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password1)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_5.setStyleSheet("color: rgb(97, 53, 131);")
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.password1_repeat = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.password1_repeat.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password1_repeat.setObjectName("password1_repeat")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.password1_repeat)
        self.registration = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.registration.setStyleSheet("color: rgb(129, 61, 156);\n"
"background-color: rgb(220, 138, 221);")
        self.registration.setObjectName("registration")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.registration)
        self.tabWidget.addTab(self.widget, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вход в систему"))
        self.label.setText(_translate("MainWindow", "Логин:"))
        self.label_2.setText(_translate("MainWindow", "Пароль:"))
        self.entry.setText(_translate("MainWindow", "Войти"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Вход в систему"))
        self.label_3.setText(_translate("MainWindow", "Логин:"))
        self.label_4.setText(_translate("MainWindow", "Пароль:"))
        self.label_5.setText(_translate("MainWindow", "Повторите пароль:"))
        self.registration.setText(_translate("MainWindow", "Зарегистрироваться"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "Регистрация"))
